### ISSUE TITLE
Unhandled Exception: System.IO.IOException: The handle is invalid.

### ISSUE THREAD

**Issue by aboodh95** [dwmkerr/consolecontrol#39] opened 2019-04-04 13:30 UTC
Hi,

I'm getting this error once the console is launched,

**Comment by dwmkerr** [comment] 2019-04-05 02:11
Can you paste the entire stack-trace please, and describe whether it is WPF/WinForms etc?

**Comment by aboodh95** [comment] 2019-04-06 13:20
Hi,

I'm using 1.1 V on WinForms 
Error Message: 
`Preparing to run C:\Users\Abood\source\repos\Server.Processes.Manager\InvoiceTaxTrigger\bin\Debug\InvoiceTaxTrigger.exe.

Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.Clear()
   at InvoiceTaxTrigger.Program.Main(String[] args) in C:\Users\Abood\source\repos\Server.Processes.Manager\InvoiceTaxTrigger\Program.cs:line 22

C:\Users\Abood\source\repos\Server.Processes.Manager\InvoiceTaxTrigger\bin\Debug\InvoiceTaxTrigger.exe exited.`

**Comment by dwmkerr** [comment] 2019-04-07 04:05
Got it- can you try the latest version, 1.2.1?

**Comment by aboodh95** [comment] 2019-04-07 04:51
Hi,

1.2.1 is not showing for me
![image](https://user-images.githubusercontent.com/12459798/55678891-5319e480-5912-11e9-8775-625a4184345c.png)

**Comment by dwmkerr** [comment] 2019-04-08 12:51
So sorry @aboodh95 you are right, I'd forgotten to publish the latest version! It's fixed now, you should be able to find it online now:

https://www.nuget.org/packages/ConsoleControl.WPF/1.2.1

**Comment by aboodh95** [comment] 2019-04-08 12:57
Hi,

Thank you so much, I installed it, but I got the same error, now with the line number in my code, at that line their Console.Clear();, since i comment that line it did work, so maybe you have to check that

**Comment by dwmkerr** [comment] 2019-04-10 13:41
OK cool - I'm going to rename this issue and keep it open to see if I can get to the root cause.

Can you tell me exactly what line you commented out?

**Comment by aboodh95** [comment] 2019-04-10 13:42
Hi,

If you want i will close the issue and open another one

**Closed** 2019-04-10 13:43 UTC
